name: flask project workflow

on:
  push:
    branches:
      - master

jobs:
  test_flask_app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
          
      - name: Install Dependencies
        run: |
          pip install flask
          pip install pytest

      - name: Run Test Cases
        run: pytest -v -s
      